name: nightly-beta-scheduler

on:
  schedule:
    - cron: "* * * * *"
      timezone: "America/Los_Angeles"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release-bot beta
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "sdk-release",
              client_payload: {
                operation: "beta",
                "schedule-id": "nightly-beta"
              }
            });
